spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akvamarinel/spring-cloud-config-git-repo.git
          default-label: master

server:
  port: 8888

